environment = "PYTHONPATH='/lustre/fs24/group/cqta/tangelides/anaconda3:$PYTHONPATH'"

executable = /lustre/fs24/group/cqta/tangelides/anaconda3/bin/python3.9

arguments = /lustre/fs24/group/cqta/tangelides/Parallelize_Cellular_Automata/main.py 
 
transfer_input_files = /lustre/fs24/group/cqta/tangelides/Parallelize_Cellular_Automata/main.py 

should_transfer_files = IF_NEEDED

request_memory = 3G 

error = /lustre/fs24/group/cqta/tangelides/Logs/$(Cluster)_$(Process)_numba_gpu_timed.error

output = /lustre/fs24/group/cqta/tangelides/Logs/$(Cluster)_$(Process)_numba_gpu_timed.out

log = /lustre/fs24/group/cqta/tangelides/Logs/$(Cluster)_$(Process)_numba_gpu_timed.log

queue